import React from "react";
import styled from "styled-components";
import { fonts } from "../../styles";

export default function Voorwaarden() {
    return (
        <Container>
            <Main>
                <h1>ALGEMENE VOORWAARDEN FLEXIBLE CHEF</h1>

                <h2>I. DEFINITIES</h2>

                <p>
                    1. Flexible chef: Flexible chef, GEVESTIGD TE purmerend
                    ONDER KVK NR. [nummer] <br />
                    2. KLANT: DEGENE MET WIE Flexible chef EEN OVEREENKOMST IS
                    AANGEGAAN. <br />
                    3. PARTIJEN: Flexible chef EN KLANT SAMEN. <br />
                    4. CONSUMENT: EEN KLANT DIE TEVENS EEN INDIVIDU IS EN DIE
                    ALS PRIVÉ PERSOON HANDELT.
                </p>

                <h2>II. TOEPASSELIJKHEID ALGEMENE VOORWAARDEN</h2>

                <p>
                    1. DEZE VOORWAARDEN ZIJN VAN TOEPASSING OP ALLE OFFERTES,
                    AANBIEDINGEN, WERKZAAMHEDEN, BESTELLINGEN, OVEREENKOMSTEN EN
                    LEVERINGEN VAN DIENSTEN OF PRODUCTEN DOOR OF NAMENS Flexible
                    chef. <br />
                    2. PARTIJEN KUNNEN ALLEEN AFWIJKEN VAN DEZE VOORWAARDEN ALS
                    ZIJ DAT UITDRUKKELIJK EN SCHRIFTELIJK ZIJN OVEREENGEKOMEN.
                    <br />
                    3. PARTIJEN SLUITEN DE TOEPASSELIJKHEID VAN AANVULLENDE
                    EN/OF AFWIJKENDE ALGEMENE VOORWAARDEN VAN DE KLANT OF VAN
                    DERDEN UITDRUKKELIJK UIT.
                </p>

                <h2>III. PRIJZEN</h2>

                <p>
                    1. ALLE PRIJZEN DIE Flexible chef HANTEERT ZIJN IN EURO’S,
                    ZIJN EXCLUSIEF BTW EN EXCLUSIEF EVENTUELE OVERIGE KOSTEN
                    ZOALS ADMINISTRATIEKOSTEN, HEFFINGEN EN REIS-, VERZEND- OF
                    TRANSPORTKOSTEN, TENZIJ UITDRUKKELIJK ANDERS VERMELD OF
                    ANDERS OVEREENGEKOMEN. <br />
                    2. ALLE PRIJZEN OP DIE Flexible chef HANTEERT VOOR ZIJN
                    PRODUCTEN OF DIENSTEN, OP ZIJN WEBSITE OF DIE ANDERSZINS
                    KENBAAR ZIJN GEMAAKT, KAN Flexible chef TE ALLEN TIJDE
                    WIJZIGEN. <br />
                    3. VERHOGINGEN VAN DE KOSTPRIJZEN VAN PRODUCTEN OF
                    ONDERDELEN DAARVAN, DIE Flexible chef NIET KON VOORZIEN TEN
                    TIJDE VAN HET DOEN VAN DE AANBIEDING C.Q. HET TOT STAND
                    KOMEN VAN DE OVEREENKOMST, KUNNEN AANLEIDING GEVEN TOT
                    PRIJSVERHOGINGEN. <br />
                    4. DE CONSUMENT HEEFT HET RECHT OM EEN OVEREENKOMST TE
                    ONTBINDEN ALS GEVOLG VAN EEN PRIJSVERHOGING ZOALS BEDOELD IN
                    LID 3, TENZIJ DE VERHOGING HET GEVOLG IS VAN EEN WETTELIJKE
                    REGELING. <br />
                    5. DE PRIJS MET BETREKKING TOT EEN DIENSTVERLENING WORDT
                    DOOR Flexible chef VASTGESTELD OP GROND VAN DE WERKELIJK
                    BESTEDE UREN. <br />
                    6. DE PRIJS WORDT BEREKEND VOLGENS DE GEBRUIKELIJKE
                    UURTARIEVEN VAN Flexible chef, GELDEND VOOR DE PERIODE
                    WAARIN HIJ DE WERKZAAMHEDEN VERRICHT, TENZIJ EEN AFWIJKEND
                    UURTARIEF IS OVEREENGEKOMEN.
                    <br />
                    7. INDIEN PARTIJEN VOOR EEN DIENSTVERLENING DOOR Flexible
                    chef EEN TOTAALBEDRAG ZIJN OVEREENGEKOMEN, IS DIT ALTIJD EEN
                    RICHTPRIJS, TENZIJ PARTIJEN UITDRUKKELIJK EN SCHRIFTELIJK
                    EEN VASTE PRIJS, WAARVAN NIET KAN WORDEN AFGEWEKEN, ZIJN
                    OVEREENGEKOMEN. <br />
                    8. Flexible chef IS GERECHTIGD OM TOT 10% VAN DE RICHTPRIJS
                    AF TE WIJKEN. <br />
                    9. INDIEN DE RICHTPRIJS MEER DAN 10% HOGER UIT GAAT VALLEN,
                    DIENT Flexible chef DE KLANT TIJDIG TE LATEN WETEN WAAROM
                    EEN HOGERE PRIJS GERECHTVAARDIGD IS. <br />
                    10. INDIEN DE RICHTPRIJS MEER DAN 10% HOGER UIT GAAT VALLEN,
                    HEEFT DE KLANT HET RECHT OM HET DEEL VAN DE OPDRACHT TE
                    LATEN VERVALLEN, DAT BOVEN DE RICHTPRIJS VERMEERDERD MET 10%
                    UITKOMT. <br />
                    11. Flexible chef HEEFT HET RECHT DE PRIJZEN JAARLIJKS AAN
                    TE PASSEN. <br />
                    12. VOORAFGAAND AAN DE INGANG ERVAN ZAL Flexible chef
                    PRIJSAANPASSINGEN MEEDELEN AAN DE KLANT. <br />
                    13. DE CONSUMENT HEEFT HET RECHT OM DE OVEREENKOMST MET
                    Flexible chef OP TE ZEGGEN INDIEN HIJ NIET AKKOORD GAAT MET
                    DE PRIJSVERHOGING.
                </p>

                <h2>IV. GEVOLGEN NIET TIJDIG BETALEN</h2>

                <p>
                    1. BETAALT DE KLANT NIET BINNEN DE OVEREENGEKOMEN TERMIJN,
                    DAN IS Flexible chef GERECHTIGD EEN RENTE VAN 1% PER MAAND
                    IN REKENING TE BRENGEN VANAF DE DAG DAT DE KLANT IN VERZUIM
                    IS, WAARBIJ EEN GEDEELTE VAN EEN MAAND VOOR EEN HELE MAAND
                    WORDT GEREKEND. <br />
                    2. WANNEER DE KLANT IN VERZUIM IS, IS HIJ BOVENDIEN
                    BUITENGERECHTELIJKE INCASSOKOSTEN EN EVENTUELE
                    SCHADEVERGOEDING VERSCHULDIGD AAN Flexible chef. <br />
                    3. DE INCASSOKOSTEN WORDEN BEREKEND AAN DE HAND VAN HET
                    BESLUIT VERGOEDING VOOR BUITENGERECHTELIJKE INCASSOKOSTEN.{" "}
                    <br />
                    4. WANNEER DE KLANT NIET TIJDIG BETAALT, MAG Flexible chef
                    ZIJN VERPLICHTINGEN OPSCHORTEN TOTDAT DE KLANT AAN ZIJN
                    BETALINGSVERPLICHTING HEEFT VOLDAAN. <br />
                    5. IN GEVAL VAN LIQUIDATIE, FAILLISSEMENT, BESLAG OF
                    SURSEANCE VAN BETALING AAN DE ZIJDE VAN DE KLANT, ZIJN DE
                    VORDERINGEN VAN Flexible chef OP DE KLANT ONMIDDELLIJK
                    OPEISBAAR. <br />
                    WEIGERT DE KLANT ZIJN MEDEWERKING AAN DE UITVOERING VAN DE
                    OVEREENKOMST DOOR Flexible chef, DAN IS HIJ NOG STEEDS
                    VERPLICHT DE AFGESPROKEN PRIJS AAN Flexible chef TE BETALEN.
                </p>

                <h2>V. RECHT VAN RECLAME</h2>

                <p>
                    1. ZODRA DE KLANT IN VERZUIM IS, IS flexible CHEF GERECHTIGD
                    HET RECHT VAN RECLAME IN TE ROEPEN TEN AANZIEN VAN DE
                    ONBETAALDE AAN DE KLANT GELEVERDE PRODUCTEN. <br />
                    2. flexible CHEF ROEPT HET RECHT VAN RECLAME IN DOOR MIDDEL
                    VAN EEN SCHRIFTELIJKE OF ELEKTRONISCHE MEDEDELING. <br />
                    3. ZODRA DE KLANT OP DE HOOGTE IS GESTELD VAN HET INGEROEPEN
                    RECHT VAN RECLAME, DIENT DE KLANT DE PRODUCTEN WAAR DIT
                    RECHT BETREKKING OP HEEFT, ONMIDDELLIJK TE RETOURNEREN AAN
                    flexible CHEF, TENZIJ PARTIJEN HIEROVER ANDERE AFSPRAKEN
                    MAKEN. <br />
                    4. DE KOSTEN VOOR HET TERUGHALEN OF -BRENGEN VAN DE
                    PRODUCTEN KOMEN VOOR REKENING VAN DE KLANT.
                </p>

                <h2>VI. OPSCHORTINGSRECHT</h2>

                <p>
                    1. TENZIJ DE KLANT EEN CONSUMENT IS, DOET DE KLANT AFSTAND
                    VAN HET RECHT OM DE NAKOMING VAN ENIGE UIT DEZE OVEREENKOMST
                    VOORTVLOEIENDE VERBINTENIS OP TE SCHORTEN.
                </p>

                <h2>VII. RETENTIERECHT</h2>

                <p>
                    1. flexible CHEF KAN EEN BEROEP DOEN OP ZIJN RETENTIERECHT
                    EN IN DAT GEVAL PRODUCTEN VAN DE KLANT ONDER ZICH HOUDEN,
                    TOTDAT DE KLANT ALLE NOG OPENSTAANDE REKENINGEN TEN AANZIEN
                    VAN flexible CHEF HEEFT VOLDAAN, TENZIJ DE KLANT VOOR DIE
                    KOSTEN VOLDOENDE ZEKERHEID HEEFT GESTELD. <br />
                    2. DE RETENTIERECHT GELDT EVENEENS OP GROND VAN EERDERE
                    OVEREENKOMSTEN WAARUIT DE KLANT NOG BETALINGEN VERSCHULDIGD
                    IS AAN flexible CHEF. <br />
                    3. flexible CHEF IS NOOIT AANSPRAKELIJK VOOR EVENTUELE
                    SCHADE DIE DE KLANT MOGELIJKERWIJS LIJDT ALS GEVOLG VAN HET
                    GEBRUIKMAKEN VAN ZIJN RETENTIERECHT.
                </p>

                <h2>VIII. VERREKENING</h2>

                <p>
                    1. TENZIJ DE KLANT EEN CONSUMENT IS, DOET DE KLANT AFSTAND
                    VAN ZIJN RECHT OM EEN SCHULD AAN flexible CHEF TE VERREKENEN
                    MET EEN VORDERING OP flexible CHEF.
                </p>

                <h2>IX. EIGENDOMSVOORBEHOUD</h2>

                <p>
                    1. flexible CHEF BLIJFT EIGENAAR VAN ALLE GELEVERDE
                    PRODUCTEN TOTDAT DE KLANT VOLLEDIG HEEFT VOLDAAN AAN AL ZIJN
                    BETALINGSVERPLICHTINGEN TEN AANZIEN VAN flexible CHEF OP
                    GROND VAN WAT VOOR MET flexible CHEF GESLOTEN OVEREENKOMST
                    DAN OOK, MET INBEGRIP VAN VORDERINGEN INZAKE HET
                    TEKORTSCHIETEN IN DE NAKOMING. <br />
                    2. TOT DIE TIJD KAN flexible CHEF ZICH BEROEPEN OP ZIJN
                    EIGENDOMSVOORBEHOUD EN DE ZAKEN TERUGNEMEN. <br />
                    3. VOORDAT HET EIGENDOM IS OVERGEGAAN OP DE KLANT, MAG DE
                    KLANT DE PRODUCTEN NIET VERPANDEN, VERKOPEN, VERVREEMDEN OF
                    ANDERSZINS BEZWAREN. <br />
                    4. INDIEN flexible CHEF EEN BEROEP DOET OP ZIJN
                    EIGENDOMSVOORBEHOUD, GELDT DE OVEREENKOMST ALS ONTBONDEN EN
                    HEEFT flexible CHEF HET RECHT OM SCHADEVERGOEDING, GEDERFDE
                    WINST EN RENTE TE VORDEREN.
                </p>

                <h2>X. VERZEKERING</h2>

                <p>
                    1. DE KLANT VERPLICHT ZICH DE VOLGENDE ZAKEN VOLDOENDE TE
                    VERZEKEREN EN VERZEKERD TE HOUDEN TEGEN ONDER ANDERE BRAND,
                    ONTPLOFFINGS- EN WATERSCHADE EVENALS DIEFSTAL: <br />
                    2. GELEVERDE ZAKEN DIE NOODZAKELIJK ZIJN VOOR DE UITVOERING
                    VAN DE ONDERLIGGENDE OVEREENKOMST <br />
                    3. ZAKEN VAN flexible CHEF DIE BIJ DE KLANT AANWEZIG ZIJN{" "}
                    <br />
                    4. ZAKEN DIE ONDER EIGENDOMSVOORBEHOUD ZIJN GELEVERD <br />
                    5. DE KLANT GEEFT OP EERSTE VERZOEK VAN flexible CHEF DE
                    POLIS VAN DEZE VERZEKERINGEN TER INZAGE.
                </p>

                <h2>XI. BEWARING</h2>

                <p>
                    1. INDIEN DE KLANT BESTELDE PRODUCTEN PAS LATER AFNEEMT DAN
                    DE OVEREENGEKOMEN LEVERINGSDATUM, IS HET RISICO VAN EEN
                    EVENTUEEL KWALITEITSVERLIES GEHEEL VOOR DE KLANT. <br />
                    2. EVENTUELE EXTRA KOSTEN ALS GEVOLG VAN VOORTIJDIGE DANWEL
                    VERLATE AFNAME VAN PRODUCTEN KOMEN GEHEEL VOOR REKENING VAN
                    DE KLANT.
                </p>

                <h2>XII. GARANTIE</h2>

                <p>
                    1. WANNEER PARTIJEN EEN OVEREENKOMST MET EEN DIENSTVERLENEND
                    KARAKTER ZIJN AANGEGAAN, BEVAT DEZE VOOR flexible CHEF ENKEL
                    INSPANNINGSVERPLICHTINGEN, GEEN RESULTAATSVERPLICHTINGEN.
                    <br /> 2. DE GARANTIE MET BETREKKING TOT PRODUCTEN IS
                    UITSLUITEND VAN TOEPASSING OP DEFECTEN, VEROORZAAKT DOOR
                    ONDEUGDELIJK(E) FABRICAGE, CONSTRUCTIE OF MATERIAAL. <br />
                    3. DE GARANTIE GELDT NIET IN HET GEVAL VAN NORMALE SLIJTAGE
                    EN VAN SCHADE ONTSTAAN ALS GEVOLG VAN ONGEVALLEN,
                    AANGEBRACHTE WIJZIGINGEN AAN HET PRODUCT, NALATIGHEID OF
                    ONDESKUNDIG GEBRUIK DOOR DE KLANT, ALSMEDE WANNEER DE
                    OORZAAK VAN HET DEFECT NIET DUIDELIJK KAN WORDEN
                    VASTGESTELD. <br />
                    4. HET RISICO VAN VERLIES, BESCHADIGING OF DIEFSTAL VAN DE
                    PRODUCTEN DIE HET VOORWERP ZIJN VAN EEN OVEREENKOMST TUSSEN
                    PARTIJEN, GAAT OVER OP DE KLANT OP HET MOMENT WAAROP DEZE
                    JURIDISCH EN/OF FEITELIJK WORDEN GELEVERD, ALTHANS IN DE
                    MACHT VAN DE KLANT KOMEN OF VAN EEN DERDE DIE HET PRODUCT
                    TEN BEHOEVE VAN DE KLANT IN ONTVANGST NEEMT.
                </p>

                <h2>XIII. UITVOERING VAN DE OVEREENKOMST</h2>

                <p>
                    1. flexible CHEF VOERT DE OVEREENKOMST NAAR BESTE INZICHT EN
                    VERMOGEN EN OVEREENKOMSTIG DE EISEN VAN GOED VAKMANSCHAP
                    UIT. <br />
                    2. flexible CHEF HEEFT HET RECHT OM DE OVEREENGEKOMEN
                    DIENSTVERLENING (GEDEELTELIJK) TE LATEN VERRICHTEN DOOR
                    DERDEN. <br />
                    3. DE UITVOERING VAN DE OVEREENKOMST GESCHIEDT IN ONDERLING
                    OVERLEG EN NA SCHRIFTELIJK AKKOORD EN BETALING VAN HET
                    EVENTUEEL AFGESPROKEN VOORSCHOT DOOR DE KLANT. <br />
                    4. HET IS DE VERANTWOORDELIJKHEID VAN DE KLANT DAT flexible
                    CHEF TIJDIG KAN BEGINNEN AAN DE UITVOERING VAN DE
                    OVEREENKOMST.
                    <br />
                    5. INDIEN DE KLANT ER NIET VOOR HEEFT GEZORGD DAT flexible
                    CHEF TIJDIG KAN BEGINNEN AAN DE UITVOERING VAN DE
                    OVEREENKOMST, KOMEN DE DAARUIT VOORTVLOEIENDE EXTRA KOSTEN
                    EN/OF EXTRA UREN VOOR REKENING VAN DE KLANT.
                </p>

                <h2>XIV. INFORMATIEVERSTREKKING DOOR DE KLANT</h2>

                <p>
                    1. DE KLANT STELT ALLE INFORMATIE, GEGEVENS EN BESCHEIDEN
                    DIE RELEVANT ZIJN VOOR DE CORRECTE UITVOERING VAN DE
                    OVEREENKOMST TIJDIG EN IN GEWENSTE VORM EN OP GEWENSTE WIJZE
                    BESCHIKBAAR AAN flexible CHEF. <br />
                    2. DE KLANT STAAT IN VOOR DE JUISTHEID, VOLLEDIGHEID EN
                    BETROUWBAARHEID VAN DE TER BESCHIKKING GESTELDE INFORMATIE,
                    GEGEVENS EN BESCHEIDEN, OOK INDIEN DEZE VAN DERDEN AFKOMSTIG
                    ZIJN, VOOR ZOVER UIT DE AARD VAN DE OVEREENKOMST NIET ANDERS
                    VOORTVLOEIT. <br />
                    3. INDIEN EN VOOR ZOVER DE KLANT DIT VERZOEKT, RETOURNEERT
                    flexible CHEF DE BETREFFENDE BESCHEIDEN. <br />
                    4. STELT DE KLANT NIET, NIET TIJDIG OF NIET BEHOORLIJK DE
                    DOOR flexible CHEF TREDELIJKERWIJS VERLANGDE INFORMATIE,
                    GEGEVENS OF BESCHEIDEN BESCHIKBAAR EN LOOPT DE UITVOERING
                    VAN DE OVEREENKOMST HIERDOOR VERTRAGING OP, DAN KOMEN DE
                    DAARUIT VOORTVLOEIENDE EXTRA KOSTEN EN EXTRA UREN VOOR
                    REKENING VAN DE KLANT.
                </p>

                <h2>XV. DUUR VAN DE OVEREENKOMST</h2>

                <p>
                    1. DE OVEREENKOMST TUSSEN flexible CHEF EN DE KLANT WORDT
                    AANGEGAAN VOOR ONBEPAALDE TIJD, TENZIJ UIT DE AARD VAN DE
                    OVEREENKOMST IETS ANDERS VOORTVLOEIT OF PARTIJEN
                    UITDRUKKELIJK EN SCHRIFTELIJK ANDERS ZIJN OVEREENGEKOMEN.{" "}
                    <br />
                    2. INDIEN EEN OVEREENKOMST VOOR BEPAALDE TIJD IS AANGEGAAN,
                    DAN WORDT DEZE NA AFLOOP VAN DE TERMIJN STILZWIJGEND OMGEZET
                    IN EEN OVEREENKOMST VOOR ONBEPAALDE TIJD, TENZIJ 1 VAN DE
                    PARTIJEN DE OVEREENKOMST OPZEGT MET INACHTNEMING VAN EEN
                    OPZEGTERMIJN VAN 2 MAAND(EN), C.Q. EEN CONSUMENT DE
                    OVEREENKOMST OPZEGT MET INACHTNEMING VAN EEN OPZEGTERMIJN
                    VAN 1 MAAND DAN EINDIGT DE OVEREENKOMST VAN RECHTSWEGE.{" "}
                    <br />
                    3. ZIJN PARTIJEN BINNEN DE LOOPTIJD VAN DE OVEREENKOMST VOOR
                    DE VOLTOOIING VAN BEPAALDE WERKZAAMHEDEN EEN TERMIJN
                    OVEREENGEKOMEN, DAN IS DIT NOOIT EEN FATALE TERMIJN. BIJ
                    OVERSCHRIJDING VAN DEZE TERMIJN MOET DE KLANT FLEXIBLE CHEF
                    SCHRIFTELIJK IN GEBREKE STELLEN.
                </p>

                <h2>XVI. OPZEGGEN OVEREENKOMST VOOR ONBEPAALDE TIJD</h2>

                <p>
                    1. DE KLANT KAN EEN OVEREENKOMST DIE VOOR ONBEPAALDE TIJD IS
                    AANGEGAAN TE ALLEN TIJDE OPZEGGEN MET INACHTNEMING VAN EEN
                    OPZEGTERMIJN VAN 2 MAANDEN. <br />
                    2. EEN CONSUMENT HEEFT HET RECHT EEN OVEREENKOMST VOOR
                    ONBEPAALDE TIJD OP TE ZEGGEN MET INACHTNEMING VAN EEN
                    OPZEGTERMIJN VAN 1 MAAND.
                </p>

                <h2>XVII. INTELLECTUEEL EIGENDOM</h2>

                <p>
                    1. FLEXIBLE CHEF BEHOUDT ALLE INTELLECTUELE EIGENDOMSRECHTEN
                    (WAARONDER AUTEURSRECHT, OCTROOIRECHT, MERKENRECHT,
                    TEKENINGEN- EN MODELLENRECHT, ETC.) OP ALLE ONTWERPEN,
                    TEKENINGEN, GESCHRIFTEN, DRAGERS MET GEGEVENS OF ANDERE
                    INFORMATIE, OFFERTES, AFBEELDINGEN, SCHETSEN, MODELLEN,
                    MAQUETTES, ETC., TENZIJ PARTIJEN SCHRIFTELIJK ANDERS ZIJN
                    OVEREENGEKOMEN. <br />
                    2. DE KLANT MAG GENOEMDE INTELLECTUELE EIGENDOMSRECHTEN NIET
                    ZONDER VOORAFGAANDE SCHRIFTELIJKE TOESTEMMING VAN FLEXIBLE
                    CHEF (LATEN) KOPIËREN, AAN DERDEN TONEN EN/OF TER
                    BESCHIKKING STELLEN OF OP ANDERE WIJZE GEBRUIKEN.
                </p>

                <h2>XVIII. GEHEIMHOUDING</h2>

                <p>
                    1. DE KLANT HOUDT IEDERE INFORMATIE DIE HIJ (IN WELKE VORM
                    DAN OOK) VAN FLEXIBLE CHEF ONTVANGT GEHEIM. <br />
                    2. HETZELFDE GELDT VOOR ALLE ANDERE INFORMATIE BETREFFENDE
                    FLEXIBLE CHEF WAARVAN HIJ WEET OF REDELIJKERWIJS KAN
                    VERMOEDEN DAT DEZE GEHEIM OF VERTROUWELIJK IS, DAN WEL
                    WAARVAN HIJ KAN VERWACHTEN DAT VERSPREIDING ERVAN FLEXIBLE
                    CHEF SCHADE KAN BEROKKENEN. <br />
                    3. DE KLANT NEEMT ALLE NODIGE MAATREGELEN OM TE WAARBORGEN
                    DAT HIJ DE IN LID 1 EN 2 GENOEMDE INFORMATIE OOK GEHEIM
                    HOUDT. <br />
                    4. DE IN DIT ARTIKEL OMSCHREVEN GEHEIMHOUDINGSPLICHT GELDT
                    NIET VOOR INFORMATIE: <br />• DIE AL OPENBAAR WAS VOORDAT DE
                    KLANT DEZE INFORMATIE VERNAM OF DIE LATER OPENBAAR IS
                    GEWORDEN ZONDER DAT DIT HET GEVOLG WAS VAN EEN SCHENDING VAN
                    DE GEHEIMHOUDINGSPLICHT VAN DE KLANT <br />• DIE DOOR DE
                    KLANT OPENBAAR GEMAAKT WORDT OP GROND VAN EEN WETTELIJKE
                    PLICHT <br />• DE IN DIT ARTIKEL OMSCHREVEN
                    GEHEIMHOUDINGSPLICHT GELDT VOOR DE DUUR VAN DE ONDERLIGGENDE
                    OVEREENKOMST EN VOOR EEN PERIODE VAN 3 JAAR NA AFLOOP
                    DAARVAN.
                </p>

                <h2>XIX. BOETEBEDING</h2>

                <p>
                    1. INDIEN DE KLANT HET ARTIKEL VAN DEZE ALGEMENE VOORWAARDEN
                    OVER GEHEIMHOUDING OF OVER INTELLECTUEEL EIGENDOM
                    OVERTREEDT, DAN VERBEURT HIJ TEN BEHOEVE VAN FLEXIBLE CHEF
                    EEN ONMIDDELLIJK OPEISBARE BOETE VAN €5.000 VOOR ELKE
                    OVERTREDING EN DAARNAAST EEN BEDRAG VAN 5% VAN HET HIERBOVEN
                    GENOEMDE BEDRAG VOOR ELKE DAG DAT DIE OVERTREDING
                    VOORTDUURT. <br />
                    2. VOOR HET VERBEUREN VAN DEZE BOETE IS GEEN VOORAFGAANDE
                    INGEBREKESTELLING OF GERECHTELIJKE PROCEDURE NODIG. OOK
                    HOEFT ER GEEN SPRAKE TE ZIJN VAN ENIGE VORM VAN SCHADE.{" "}
                    <br />
                    3. HET VERBEUREN VAN DE IN HET EERSTE LID VAN DIT ARTIKEL
                    BEDOELDE BOETE DOET GEEN AFBREUK AAN DE OVERIGE RECHTEN VAN
                    FLEXIBLE CHEF WAARONDER ZIJN RECHT OM NAAST DE BOETE
                    SCHADEVERGOEDING TE VORDEREN.
                </p>

                <h2>XX. VRIJWARING</h2>

                <p>
                    1. DE KLANT VRIJWAART FLEXIBLE CHEF TEGEN ALLE AANSPRAKEN
                    VAN DERDEN DIE VERBAND HOUDEN MET DE DOOR FLEXIBLE CHEF
                    GELEVERDE PRODUCTEN EN/OF DIENSTEN.
                </p>

                <h2>XXI. KLACHTEN</h2>

                <p>
                    1. DE KLANT DIENT EEN DOOR FLEXIBLE CHEF GELEVERD PRODUCT OF
                    VERLEENDE DIENST ZO SPOEDIG MOGELIJK TE ONDERZOEKEN OP
                    EVENTUELE TEKORTKOMINGEN. <br />
                    2. BEANTWOORDT EEN GELEVERD PRODUCT OF VERLEENDE DIENST NIET
                    AAN HETGEEN DE KLANT REDELIJKERWIJS VAN DE OVEREENKOMST
                    MOCHT VERWACHTEN, DAN DIENT DE KLANT FLEXIBLE CHEF DAARVAN
                    ZO SPOEDIG MOGELIJK, DOCH IN IEDER GEVAL BINNEN 1 MAAND NA
                    CONSTATERING VAN DE TEKORTKOMINGEN, OP DE HOOGTE TE STELLEN.{" "}
                    <br />
                    3. CONSUMENTEN DIENEN FLEXIBLE CHEF UITERLIJK BINNEN 2
                    MAANDEN NA CONSTATERING VAN DE TEKORTKOMINGEN HIERVAN OP DE
                    HOOGTE TE STELLEN. <br />
                    4. DE KLANT GEEFT DAARBIJ EEN ZO GEDETAILLEERD MOGELIJKE
                    OMSCHRIJVING VAN DE TEKORTKOMING, ZODAT FLEXIBLE CHEF IN
                    STAAT IS HIEROP ADEQUAAT TE REAGEREN. <br />
                    5. DE KLANT DIENT AAN TE TONEN DAT DE KLACHT BETREKKING
                    HEEFT OP EEN OVEREENKOMST TUSSEN PARTIJEN. <br />
                    6. INDIEN EEN KLACHT BETREKKING HEEFT OP LOPENDE
                    WERKZAAMHEDEN, KAN DIT ER IN IEDER GEVAL NIET TOE LEIDEN DAT
                    FLEXIBLE CHEF GEHOUDEN KAN WORDEN OM ANDERE WERKZAAMHEDEN TE
                    VERRICHTEN DAN ZIJN OVEREENGEKOMEN.
                </p>

                <h2>XXII. INGEBREKESTELLING</h2>

                <p>
                    1. DE KLANT DIENT INGEBREKESTELLINGEN SCHRIFTELIJK KENBAAR
                    TE MAKEN AAN FLEXIBLE CHEF. <br />
                    2. HET IS DE VERANTWOORDELIJKHEID VAN DE KLANT DAT EEN
                    INGEBREKESTELLING FLEXIBLE CHEF OOK DAADWERKELIJK (TIJDIG)
                    BEREIKT.
                </p>
                <h2>XXIII. HOOFDELIJKE AANSPRAKELIJKHEID KLANT</h2>

                <p>
                    1. ALS FLEXIBLE CHEF EEN OVEREENKOMST AANGAAT MET MEERDERE
                    KLANTEN, IS IEDER VAN HEN HOOFDELIJK AANSPRAKELIJK VOOR DE
                    VOLLEDIGE BEDRAGEN DIE ZIJ OP GROND VAN DIE OVEREENKOMST AAN
                    FLEXIBLE CHEF VERSCHULDIGD ZIJN.
                </p>

                <h2>XIV. AANSPRAKELIJKHEID FLEXIBLE CHEF</h2>

                <p>
                    1. FLEXIBLE CHEF IS UITSLUITEND AANSPRAKELIJK VOOR ENIGE
                    SCHADE DIE DE KLANT LIJDT INDIEN EN VOOR ZOVER DIE SCHADE IS
                    VEROORZAAKT DOOR OPZET OF BEWUSTE ROEKELOOSHEID. <br />
                    2. INDIEN FLEXIBLE CHEF AANSPRAKELIJK IS VOOR ENIGE SCHADE,
                    IS HET SLECHTS AANSPRAKELIJK VOOR DIRECTE SCHADE DIE
                    VOORTVLOEIT UIT OF VERBAND HOUDT MET DE UITVOERING VAN EEN
                    OVEREENKOMST.
                    <br />
                    3. FLEXIBLE CHEF IS NOOIT AANSPRAKELIJK VOOR INDIRECTE
                    SCHADE, ZOALS GEVOLGSCHADE, GEDERFDE WINST, GEMISTE
                    BESPARINGEN OF SCHADE AAN DERDEN. <br />
                    4. INDIEN FLEXIBLE CHEF AANSPRAKELIJK IS, IS DEZE
                    AANSPRAKELIJKHEID BEPERKT TOT HET BEDRAG DAT DOOR EEN
                    GESLOTEN (BEROEPS)AANSPRAKELIJKHEIDSVERZEKERING WORDT
                    UITBETAALD EN BIJ GEBREKE VAN (VOLLEDIGE) UITKERING DOOR EEN
                    VERZEKERINGSMAATSCHAPPIJ VAN HET SCHADEBEDRAG IS DE
                    AANSPRAKELIJKHEID BEPERKT TOT HET (GEDEELTE VAN HET)
                    FACTUURBEDRAG WAAROP DE AANSPRAKELIJKHEID BETREKKING HEEFT.
                    <br />
                    5. ALLE AFBEELDINGEN, FOTO’S, KLEUREN, TEKENINGEN,
                    OMSCHRIJVINGEN OP DE WEBSITE OF IN EEN CATALOGUS ZIJN
                    SLECHTS INDICATIEF EN GELDEN SLECHTS BIJ BENADERING EN
                    KUNNEN GEEN AANLEIDING ZIJN TOT SCHADEVERGOEDING EN/OF
                    (GEDEELTELIJKE) ONTBINDING VAN DE OVEREENKOMST EN/OF
                    OPSCHORTING VAN ENIGE VERPLICHTING.
                </p>

                <h2>XXV. VERVALTERMIJN</h2>

                <p>
                    1. ELK RECHT VAN DE KLANT OP SCHADEVERGOEDING VAN FLEXIBLE
                    CHEF VERVALT IN ELK GEVAL 12 MAANDEN NA DE GEBEURTENIS
                    WAARUIT DE AANSPRAKELIJKHEID DIRECT OF INDIRECT VOORTVLOEIT.
                    HIERMEE WORDT NIET UITGESLOTEN HET BEPAALDE IN ARTIKEL 6:89
                    VAN HET BURGERLIJK WETBOEK.
                </p>

                <h2>XXVI. RECHT OP ONTBINDING</h2>

                <p>
                    1. DE KLANT HEEFT HET RECHT DE OVEREENKOMST TE ONTBINDEN
                    WANNEER FLEXIBLE CHEF TOEREKENBAAR TEKORTSCHIET IN DE
                    NAKOMING VAN ZIJN VERPLICHTINGEN, TENZIJ DEZE TEKORTKOMING,
                    GEZIEN HAAR BIJZONDERE AARD OF GERINGE BETEKENIS, DE
                    ONTBINDING NIET RECHTVAARDIGT. <br />
                    2. IS DE NAKOMING VAN DE VERPLICHTINGEN DOOR FLEXIBLE CHEF
                    NIET BLIJVEND OF TIJDELIJK ONMOGELIJK, DAN KAN ONTBINDING
                    PAS PLAATSVINDEN NADAT FLEXIBLE CHEF IN VERZUIM IS. <br />
                    3. FLEXIBLE CHEF HEEFT HET RECHT DE OVEREENKOMST MET DE
                    KLANT TE ONTBINDEN, INDIEN DE KLANT ZIJN VERPLICHTINGEN UIT
                    DE OVEREENKOMST NIET VOLLEDIG OF NIET TIJDIG NAKOMT, DANWEL
                    INDIEN FLEXIBLE CHEF KENNIS HEEFT GENOMEN VAN OMSTANDIGHEDEN
                    DIE HEM GOEDE GROND GEVEN OM TE VREZEN DAT DE KLANT ZIJN
                    VERPLICHTINGEN NIET BEHOORLIJK ZAL KUNNEN NAKOMEN.
                </p>

                <h2>XXVII. OVERMACHT</h2>

                <p>
                    1. IN AANVULLING OP HET BEPAALDE IN ARTIKEL 6:75 BURGERLIJK
                    WETBOEK GELDT DAT EEN TEKORTKOMING VAN FLEXIBLE CHEF IN DE
                    NAKOMING VAN ENIGE VERPLICHTING TEN AANZIEN VAN DE KLANT
                    NIET AAN FLEXIBLE CHEF KAN WORDEN TOEGEREKEND IN EEN VAN DE
                    WIL VAN FLEXIBLE CHEF ONAFHANKELIJKE SITUATIE, WAARDOOR DE
                    NAKOMING VAN ZIJN VERPLICHTINGEN TEN AANZIEN VAN DE KLANT
                    GEHEEL OF GEDEELTELIJK WORDT VERHINDERD OF WAARDOOR DE
                    NAKOMING VAN ZIJN VERPLICHTINGEN IN REDELIJKHEID NIET VAN
                    FLEXIBLE CHEF KAN WORDEN VERLANGD. <br />
                    2. TOT DE IN LID 1 GENOEMDE OVERMACHTSITUATIE WORDEN OOK -
                    DOCH NIET UITSLUITEND - GEREKEND: NOODTOESTAND (ZOALS
                    BURGEROORLOG, OPSTAND, RELLEN, NATUURRAMPEN, ETC.);
                    WANPRESTATIES EN OVERMACHT VAN TOELEVERANCIERS, BEZORGERS OF
                    ANDERE DERDEN; ONVERWACHTE STROOM-, ELEKTRICITEITS-
                    INTERNET-, COMPUTER- EN TELECOMSTORINGEN; COMPUTERVIRUSSEN,
                    STAKINGEN, OVERHEIDSMAATREGELEN, ONVOORZIENE
                    VERVOERSPROBLEMEN, SLECHTE WEERSOMSTANDIGHEDEN EN
                    WERKONDERBREKINGEN. <br />
                    3. INDIEN ZICH EEN OVERMACHTSITUATIE VOORDOET WAARDOOR
                    FLEXIBLE CHEF 1 OF MEER VERPLICHTINGEN NAAR DE KLANT NIET
                    KAN NAKOMEN, DAN WORDEN DIE VERPLICHTINGEN OPGESCHORT TOTDAT
                    FLEXIBLE CHEF ER WEER AAN KAN VOLDOEN. <br />
                    4. VANAF HET MOMENT DAT EEN OVERMACHTSITUATIE TENMINSTE 30
                    KALENDERDAGEN HEEFT GEDUURD, MOGEN BEIDE PARTIJEN DE
                    OVEREENKOMST SCHRIFTELIJK GEHEEL OF GEDEELTELIJK ONTBINDEN.{" "}
                    <br />
                    5. FLEXIBLE CHEF IS IN EEN OVERMACHTSITUATIE GEEN ENKELE
                    (SCHADE)VERGOEDING VERSCHULDIGD, OOK NIET ALS HET ALS GEVOLG
                    VAN DE OVERMACHTTOESTAND ENIG VOORDEEL GENIET.
                </p>

                <h2>XXVIII. WIJZIGING VAN DE OVEREENKOMST</h2>

                <p>
                    1. INDIEN NA HET AFSLUITEN VAN DE OVEREENKOMST VOOR DE
                    UITVOERING ERVAN HET NODIG BLIJKT OM DE INHOUD ERVAN TE
                    WIJZIGEN OF AAN TE VULLEN, PASSEN PARTIJEN TIJDIG EN IN
                    ONDERLING OVERLEG DE OVEREENKOMST DIENOVEREENKOMSTIG AAN.
                </p>

                <h2>XXVIX. WIJZIGING ALGEMENE VOORWAARDEN</h2>

                <p>
                    1. FLEXIBLE CHEF IS GERECHTIGD DEZE ALGEMENE VOORWAARDEN TE
                    WIJZIGEN OF AAN TE VULLEN. <br />
                    2. WIJZIGINGEN VAN ONDERGESCHIKT BELANG KUNNEN TE ALLEN
                    TIJDE WORDEN DOORGEVOERD. <br />
                    3. GROTE INHOUDELIJKE WIJZIGINGEN ZAL FLEXIBLE CHEF ZOVEEL
                    MOGELIJK VOORAF MET DE KLANT BESPREKEN. <br />
                    4. CONSUMENTEN ZIJN GERECHTIGD BIJ EEN WEZENLIJKE WIJZIGING
                    VAN DE ALGEMENE VOORWAARDEN DE OVEREENKOMST OP TE ZEGGEN.
                </p>

                <h2>XXX. OVERGANG VAN RECHTEN</h2>

                <p>
                    1. RECHTEN VAN DE KLANT UIT EEN OVEREENKOMST TUSSEN PARTIJEN
                    KUNNEN NIET AAN DERDEN WORDEN OVERGEDRAGEN ZONDER DE
                    VOORAFGAANDE SCHRIFTELIJKE INSTEMMING VAN FLEXIBLE CHEF.{" "}
                    <br />
                    2. DEZE BEPALING GELDT ALS EEN BEDING MET
                    GOEDERENRECHTELIJKE WERKING ZOALS BEDOELD IN ARTIKEL 3:83,
                    TWEEDE LID, BURGERLIJK WETBOEK.
                </p>

                <h2>XXXI. GEVOLGEN NIETIGHEID OF VERNIETIGBAARHEID</h2>

                <p>
                    1. WANNEER ÉÉN OF MEERDERE BEPALINGEN VAN DEZE ALGEMENE
                    VOORWAARDEN NIETIG OF VERNIETIGBAAR BLIJKEN, DAN TAST DIT DE
                    OVERIGE BEPALINGEN VAN DEZE VOORWAARDEN NIET AAN. <br />
                    2. EEN BEPALING DIE NIETIG OF VERNIETIGBAAR IS, WORDT IN DAT
                    GEVAL VERVANGEN DOOR EEN BEPALING DIE HET DICHTST IN DE
                    BUURT KOMT VAN WAT FLEXIBLE CHEF BIJ HET OPSTELLEN VAN DE
                    VOORWAARDEN OP DAT PUNT VOOR OGEN HAD.
                </p>

                <h2>XXXII. TOEPASSELIJK RECHT EN BEVOEGDE RECHTER</h2>

                <p>
                    OP IEDERE OVEREENKOMST TUSSEN PARTIJEN IS UITSLUITEND HET
                    NEDERLANDS RECHT VAN TOEPASSING. DE NEDERLANDSE RECHTER IN
                    HET ARRONDISSEMENT WAAR FLEXIBLE CHEF IS GEVESTIGD/ PRAKTIJK
                    HOUDT/KANTOOR HOUDT IS EXCLUSIEF BEVOEGD OM KENNIS TE NEMEN
                    VAN EVENTUELE GESCHILLEN TUSSEN PARTIJEN, TENZIJ DE WET
                    DWINGEND ANDERS VOORSCHRIJFT. <br />
                    OPGESTELD OP 02.10.2020 EN GEDEPONEERD BIJ DE KVK.
                </p>
            </Main>
        </Container>
    );
}
const Container = styled.section`
    padding: 8rem 2rem;

    background-color: ${(props) => props.theme.bg};
`;
const Main = styled.section`
    * {
        ${fonts.cormorant};
        font-size: 2rem;
        color: ${(props) => props.theme.font};
        text-transform: uppercase;
    }
    h1 {
        font-family: ${fonts.rajdhani};
        font-size: 3rem;
        color: ${(props) => props.theme.primary};
    }
    h2 {
        font-family: ${fonts.rajdhani};
        color: ${(props) => props.theme.tertiary};
        font-size: 2.5rem;
    }
    ul {
        padding: 2rem;
        font-family: ${fonts.rajdhani};
        color: ${(props) => props.theme.primary};
        font-size: 1.8rem;
    }
`;
